export const AXIOS_INSTANCE_TOKEN = Symbol('AXIOS_INSTANCE_TOKEN');
export const RESILIENT_HTTP_CONFIG = Symbol('RESILIENT_HTTP_CONFIG');
export const RESILIENT_HTTP_MODULE_OPTIONS = Symbol('RESILIENT_HTTP_MODULE_OPTIONS');
