# ------------------------------------------------------------------------
FROM base-images.mgti-dal-so-art.mrshmc.com/mmc/ubuntu/nginx-jammy:1.24 AS prod

# Install jq - this is used to parse the json response from Vault in the entrpoint script
RUN apt-get update -qq \
    && apt-get install -y jq unzip \
    && apt-get clean\
    && chmod -R a+rw /usr/share/nginx/html/ \
    && mkdir -p /home/nginx/app /var/lib/nginx /var/log \
    && chmod -R a+rw /home/nginx/app \
    && chmod -R a+rw /var/lib/nginx \
    && chmod -R a+rw /var/log

# Install the platform CLI to be used for authenticating with Hashicorp Vault in AWS.
RUN PLATFORM_VAULT_CLI_VERSION=$(curl -s https://mgti-dal-so-art.mrshmc.com/artifactory/raw/mmc-platform-cli/latest.txt) \   
    && curl -L -o mpc https://mgti-dal-so-art.mrshmc.com/artifactory/raw/mmc-platform-cli/${PLATFORM_VAULT_CLI_VERSION} \
    && chmod +x mpc \
    && mv ./mpc /usr/bin

WORKDIR /home/nginx/app

ARG DIST_FOLDER_LOCATION


COPY $DIST_FOLDER_LOCATION /usr/share/nginx/html/

COPY ./deployments/docker/nginx.conf /etc/nginx/nginx.conf
COPY ./deployments/docker/entrypoint.sh ./entrypoint.sh

RUN chmod  a+xrw entrypoint.sh \
    && chown -R nginx /usr/share/nginx/html/

USER nginx

EXPOSE 8080

# Record build metadata in the image
ARG BUILD_DATE_TIME
LABEL BUILD_DATE_TIME $BUILD_DATE_TIME
ENV BUILD_DATE_TIME $BUILD_DATE_TIME

ARG BUILD_GIT_COMMIT
LABEL BUILD_GIT_COMMIT $BUILD_GIT_COMMIT
ENV BUILD_GIT_COMMIT $BUILD_GIT_COMMIT

ARG BUILD_VERSION
LABEL BUILD_VERSION $BUILD_VERSION
ENV BUILD_VERSION $BUILD_VERSION

ENV UI_APP_VERSION $BUILD_VERSION

LABEL APPLICATIONKEY "operdas1"

ENV APP_TYPE UI
ENTRYPOINT ["./entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
