import { Contact, Team } from '@operational-dashboard/shared-api-model/model/dashboard';

export const SEED_TEAMS: Omit<Team, 'id'>[] = [
    {
        name: 'Finance & Ops Team',
        department: 'Finance & Operations',
        slackChannel: '#finance-ops-support',
        emailDistributionList: 'finance-ops@company.com',
    },
    {
        name: 'HR Systems Team',
        department: 'Human Resources',
        slackChannel: '#hr-systems',
        emailDistributionList: 'hr-systems@company.com',
    },
    {
        name: 'Sales Tech Team',
        department: 'Sales & Marketing',
        slackChannel: '#sales-tech',
        emailDistributionList: 'sales-tech@company.com',
    },
    {
        name: 'IT Operations Team',
        department: 'IT Operations',
        slackChannel: '#it-ops',
        emailDistributionList: 'it-ops@company.com',
    },
    {
        name: 'Enterprise Services Team',
        department: 'Enterprise Services',
        slackChannel: '#enterprise-svc',
        emailDistributionList: 'enterprise-svc@company.com',
    },
    {
        name: 'Engineering Team',
        department: 'Engineering',
        slackChannel: '#engineering',
        emailDistributionList: 'engineering@company.com',
    },
];

export const SEED_CONTACTS: Omit<Contact, 'id'>[] = [
    {
        teamId: 'team-finance-ops',
        employeeId: 'E001',
        displayName: 'John Smith',
        email: 'john.smith@company.com',
        phone: '+1-555-0101',
        role: 'APP_OWNER',
        isPrimaryContact: true,
    },
    {
        teamId: 'team-finance-ops',
        employeeId: 'E002',
        displayName: 'Sarah Johnson',
        email: 'sarah.johnson@company.com',
        phone: '+1-555-0102',
        role: 'ON_CALL_PRIMARY',
        isPrimaryContact: false,
    },
    {
        teamId: 'team-finance-ops',
        employeeId: 'E003',
        displayName: 'Mike Davis',
        email: 'mike.davis@company.com',
        phone: '+1-555-0103',
        role: 'DBA',
        isPrimaryContact: false,
    },
    {
        teamId: 'team-hr',
        employeeId: 'E004',
        displayName: 'Emily Chen',
        email: 'emily.chen@company.com',
        phone: '+1-555-0104',
        role: 'APP_OWNER',
        isPrimaryContact: true,
    },
    {
        teamId: 'team-hr',
        employeeId: 'E005',
        displayName: 'David Wilson',
        email: 'david.wilson@company.com',
        phone: '+1-555-0105',
        role: 'ON_CALL_PRIMARY',
        isPrimaryContact: false,
    },
    {
        teamId: 'team-sales',
        employeeId: 'E006',
        displayName: 'Lisa Anderson',
        email: 'lisa.anderson@company.com',
        phone: '+1-555-0106',
        role: 'APP_OWNER',
        isPrimaryContact: true,
    },
    {
        teamId: 'team-sales',
        employeeId: 'E007',
        displayName: 'Robert Taylor',
        email: 'robert.taylor@company.com',
        phone: '+1-555-0107',
        role: 'ON_CALL_PRIMARY',
        isPrimaryContact: false,
    },
    {
        teamId: 'team-it-ops',
        employeeId: 'E008',
        displayName: 'James Brown',
        email: 'james.brown@company.com',
        phone: '+1-555-0108',
        role: 'APP_OWNER',
        isPrimaryContact: true,
    },
    {
        teamId: 'team-it-ops',
        employeeId: 'E009',
        displayName: 'Maria Garcia',
        email: 'maria.garcia@company.com',
        phone: '+1-555-0109',
        role: 'ON_CALL_PRIMARY',
        isPrimaryContact: false,
    },
    {
        teamId: 'team-enterprise',
        employeeId: 'E010',
        displayName: 'Kevin Martinez',
        email: 'kevin.martinez@company.com',
        phone: '+1-555-0110',
        role: 'APP_OWNER',
        isPrimaryContact: true,
    },
    {
        teamId: 'team-enterprise',
        employeeId: 'E011',
        displayName: 'Amanda Lee',
        email: 'amanda.lee@company.com',
        phone: '+1-555-0111',
        role: 'ON_CALL_PRIMARY',
        isPrimaryContact: false,
    },
    {
        teamId: 'team-engineering',
        employeeId: 'E012',
        displayName: 'Chris Thompson',
        email: 'chris.thompson@company.com',
        phone: '+1-555-0112',
        role: 'TECH_LEAD',
        isPrimaryContact: true,
    },
    {
        teamId: 'team-engineering',
        employeeId: 'E013',
        displayName: 'Nicole White',
        email: 'nicole.white@company.com',
        phone: '+1-555-0113',
        role: 'ON_CALL_PRIMARY',
        isPrimaryContact: false,
    },
    {
        teamId: 'team-finance-ops',
        employeeId: 'E014',
        displayName: 'Thomas Harris',
        email: 'thomas.harris@company.com',
        phone: '+1-555-0114',
        role: 'ESCALATION_MANAGER',
        isPrimaryContact: false,
    },
];
