import { Application } from '@operational-dashboard/shared-api-model/model/dashboard';

const SEED_APPLICATIONS: Omit<Application, 'id'>[] = [
    {
        name: 'SAP ERP',
        shortCode: 'SAP',
        description: 'Enterprise resource planning system for finance and operations',
        environment: 'PRODUCTION',
        tier: 1,
        businessUnit: 'Finance & Operations',
        currentStatus: 'RED',
        currentUserCount: 1204,
        monitoringSource: 'Datadog',
        teamId: 'team-finance-ops',
    },
    {
        name: 'Oracle HCM',
        shortCode: 'OHCM',
        description: 'Human capital management and talent platform',
        environment: 'PRODUCTION',
        tier: 2,
        businessUnit: 'Human Resources',
        currentStatus: 'AMBER',
        currentUserCount: 342,
        monitoringSource: 'Datadog',
        teamId: 'team-hr',
    },
    {
        name: 'Workday Payroll',
        shortCode: 'WDP',
        description: 'Payroll processing and workforce management',
        environment: 'PRODUCTION',
        tier: 1,
        businessUnit: 'Human Resources',
        currentStatus: 'AMBER',
        currentUserCount: 89,
        monitoringSource: 'Datadog',
        teamId: 'team-hr',
    },
    {
        name: 'Salesforce CRM',
        shortCode: 'SFDC',
        description: 'Customer relationship management platform',
        environment: 'PRODUCTION',
        tier: 1,
        businessUnit: 'Sales & Marketing',
        currentStatus: 'GREEN',
        currentUserCount: 3812,
        monitoringSource: 'Datadog',
        teamId: 'team-sales',
    },
    {
        name: 'ServiceNow ITSM',
        shortCode: 'SNOW',
        description: 'IT service management and incident tracking',
        environment: 'PRODUCTION',
        tier: 1,
        businessUnit: 'IT Operations',
        currentStatus: 'GREEN',
        currentUserCount: 567,
        monitoringSource: 'Datadog',
        teamId: 'team-it-ops',
    },
    {
        name: 'Microsoft 365',
        shortCode: 'M365',
        description: 'Enterprise productivity and collaboration suite',
        environment: 'PRODUCTION',
        tier: 1,
        businessUnit: 'Enterprise Services',
        currentStatus: 'GREEN',
        currentUserCount: 14209,
        monitoringSource: 'Datadog',
        teamId: 'team-enterprise',
    },
    {
        name: 'Tableau Analytics',
        shortCode: 'TAB',
        description: 'Business intelligence and data visualization',
        environment: 'PRODUCTION',
        tier: 2,
        businessUnit: 'Business Intelligence',
        currentStatus: 'GREEN',
        currentUserCount: 287,
        monitoringSource: 'Datadog',
        teamId: 'team-bi',
    },
    {
        name: 'Splunk SIEM',
        shortCode: 'SPLK',
        description: 'Security information and event management',
        environment: 'PRODUCTION',
        tier: 1,
        businessUnit: 'Information Security',
        currentStatus: 'GREEN',
        currentUserCount: 45,
        monitoringSource: 'Datadog',
        teamId: 'team-security',
    },
    {
        name: 'Cisco WebEx',
        shortCode: 'WEBX',
        description: 'Video conferencing and team collaboration',
        environment: 'PRODUCTION',
        tier: 2,
        businessUnit: 'Enterprise Services',
        currentStatus: 'GREEN',
        currentUserCount: 2103,
        monitoringSource: 'Datadog',
        teamId: 'team-enterprise',
    },
    {
        name: 'Jira Software',
        shortCode: 'JIRA',
        description: 'Project tracking and agile development tool',
        environment: 'PRODUCTION',
        tier: 3,
        businessUnit: 'Engineering',
        currentStatus: 'GREEN',
        currentUserCount: 891,
        monitoringSource: 'Datadog',
        teamId: 'team-engineering',
    },
    {
        name: 'Confluence Wiki',
        shortCode: 'CONF',
        description: 'Team knowledge base and documentation',
        environment: 'PRODUCTION',
        tier: 3,
        businessUnit: 'Engineering',
        currentStatus: 'GREEN',
        currentUserCount: 456,
        monitoringSource: 'Datadog',
        teamId: 'team-engineering',
    },
    {
        name: 'Bloomberg Terminal',
        shortCode: 'BBG',
        description: 'Financial data and trading platform',
        environment: 'PRODUCTION',
        tier: 2,
        businessUnit: 'Finance & Operations',
        currentStatus: 'GREEN',
        currentUserCount: 78,
        monitoringSource: 'Datadog',
        teamId: 'team-finance-ops',
    },
];

export default SEED_APPLICATIONS;
