name: 'Check DB Scripts'
on:
  push:

jobs:
  check_destructive_scripts:
    name: Check Destructive Scripts
    runs-on: mmc-ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Debug Git Status
        run: |
          echo "Current branches:"
          git branch -a
          echo "Current status:"
          git status
          echo "Current commits:"
          git log --oneline
          git diff --name-only HEAD^ HEAD

      - name: Print commit message
        shell: bash
        run: |
          echo "Commit message being checked:"
          echo "${{ github.event.head_commit.message }}"

      - name: Check for Destructive DB Operations
        shell: bash
        run: |
          # Check for 'destructive queries' in TypeScript files under the db folder
          if  git diff --name-only HEAD^ HEAD | grep '^db/.*\.ts$' | xargs grep -E -v '^\s*(//|/\*|\*| \*/)' | grep -E 'drop|replaceOne|unset|dropDatabase|deleteMany|deleteOne|findOneAndDelete|remove|dropCollection'; then
              echo "Your commit contains either of the operations 'drop|replaceOne|unset|dropDatabase|deleteMany|deleteOne|findOneAndDelete|remove|dropCollection' in TypeScript files under the db folder."
              echo "Warning: Drop statements were found in the modified files."
              echo "Warning: These operations would require further approval before deploying to higher environments."
              exit 1  # Exit with a non-zero status to fail the workflow
          else
              echo "No destructive operations found in TypeScript files under the db folder."
          fi
